:preinstall_operators: %preinstall_operators%

== Red Hat OpenShift Virtualization Roadshow へようこそ

OpenShift Virtualization は、最新の Kubernetes ベースのインフラストラクチャ上に仮想マシンを導入することを可能にします。新しいアプリケーションの開発と提供、および既存のアプリケーションのモダナイゼーションを可能にし、仮想マシン、コンテナ、サーバレス機能で構成されるアプリケーションを、Kubernetes ネイティブのツールとパラダイムを使用してすべて一緒に管理することができます。

このワークショップには2つのセグメントがあり、参加者全員に最後まで受講していただくことをお勧めします。

*_仮想マシンの移行_：このセクションでは、Migration Toolkit for Virtualization (MTV) を使用して、既存の VMware vSphere 環境から OpenShift Virtualization にいくつかの VM を移行します。
*_OpenShift Virtualization の基礎_：このラボでは、OpenShift Virtualization で仮想マシンを作成して使用する方法に焦点を当てます。VM の管理者 / ユーザとして実行することが予想される最も一般的なタスクをカバーしています。

さらに、あなたの特定の役割、責任、そしてあなたが興味を持つかもしれない活動を対象としたオプションのモジュールがいくつかあります。

*仮想マシン管理者*

*_仮想マシンのカスタマイズ_：仮想マシンを実行する際に最も重要なコンセプトの1つは、既存のディスクイメージから VM を実行し、VM をカスタマイズする機能を持つことです。
*_Windows 仮想マシン_：Microsoft Windows Server は一般的に使用されているオペレーティングシステムであり、これがサポートされていなければ仮想化ソリューションは完成しません！このラボでは、SysPrep によるカスタマイズを含む、Windows Server 仮想マシンのプロビジョニング方法の1つを紹介します。

*仮想インフラ管理者*

*_ベアメタル OpenShift の概要_：OpenShift のノードとリソースの管理は、あなたが慣れ親しんでいる仮想インフラのものとは異なります。このモジュールでは、サーバハードウェアの責任者である場合に重要な OpenShift のいくつかの側面と概念について説明します。
*_ネットワーク管理_：OpenShift Virtualization の仮想マシンは、デフォルトでは OpenShift 内部の SDN (Software-defined Network) に接続します。このセクションでは、VM を VLAN のような外部の物理ネットワークに接続する方法を説明します。
* _ストレージ管理_：このモジュールでは、OpenShift 上のストレージの基礎と、OpenShift Virtualization がいくつかのマシンイメージのブートソースを自動的に提供する方法を紹介します。このモジュールでは、スナップショットを使った操作の実行方法と、VM のクローンを作成する方法も紹介します。
*_バックアップとリストア_：仮想マシンとそのデータを保護することは、パフォーマンスと可用性と同じくらい重要です。このラボでは、OpenShift API for Data Protection (OADP) がストレージに依存しない方法で VM を保護する方法を紹介します。

*仮想マシンユーザ*

*_Route を使ったアプリケーションの公開_：このラボでは、Service と Route を使用してアプリケーション・コンポーネント間を内部で接続し、アプリケー ションのフロントエンドのみを外部に公開するプロセスについて説明します。
*_MetalLB を使ったアプリケーションの公開_：VM を外部の L2 ネットワークに置くことなく、VM にホストされたアプリケーションに接続性を提供することは、アプリケーションへの接続性を管理する強力な方法です。このラボでは、VM を外部ネットワークに接続することなく、データベースだけを外部に公開するプロセスを説明します。

== What is OpenShift Virtualization?

* OpenShift Virtualization is a feature of Red Hat OpenShift; it is not an add-on or a separate product and is included with all entitlements.
* All current and future subscribers receive OpenShift Virtualization as part of their OpenShift subscription. It has been generally available since OpenShift 4.5.
* OpenShift Virtualization is based on the “container-native virtualization” technology being developed upstream under the KubeVirt project, a sandbox project in the Cloud Native Computing Foundation (CNCF). 
* It leverages the Red Hat Enterprise Linux KVM hypervisor, which is a mature and highly performant open-source hypervisor used by many organizations and cloud service providers globally and which has been under development for over 15 years. 
* OpenShift Virtualization leverages the RHEL KVM hypervisor and allows the VM to be managed by Kubernetes and KubeVirt. An OpenShift Virtualization VM uses Kubernetes scheduling, network, and storage infrastructure.
* OpenShift Virtualization includes entitlements for **unlimited virtual RHEL guests**. Guest licensing for other supported operating systems will need to be purchased separately.
* OpenShift Virtualization is SVVP certified with Microsoft for Windows guest support per the same rules that apply to Red Hat’s other KVM virtualization offerings.
* OpenShift Virtualization is only supported on bare metal physical servers, typically on-premises or dedicated hosting. Support for other topologies (OpenShift on virtualized infrastructure like RHV or vSphere, OpenShift on public cloud) is not supported at this time.

OpenShift Virtualization allows OpenShift to deploy, manage, and connect virtual machines to an OpenShift cluster. This includes the ability to connect to and manage those VMs using Kubernetes-native methods and take advantage of OpenShift features like Pipelines, GitOps, Service Mesh, and more.

== Why switch from a traditional VM platform?

**Adopt cloud-native development and/or cloud-native operations:**
Red Hat OpenShift helps your team build applications with speed, agility, confidence, and choice. Code in production mode, anywhere you choose to build. Get back to doing work that matters.

**Complete app dev stack:**
Red Hat OpenShift Dev Spaces (formerly Red Hat CodeReady Workspaces), Runtimes, Integration and Process Automation, Serverless, Pipelines, and more with security throughout.

**Shift infrastructure spend to innovation:**
OpenShift native architecture changes the heavyweight cost structure from SDDC legacy to lightweight container-native frameworks.

**Risk mitigation:**
With OpenShift support for on-premises and public cloud options, OpenShift is insurance against public cloud lock-in. 

**Independent from infrastructure:**
Red Hat OpenShift runs consistently on bare metal, on-premises virtualization, or public cloud for ultimate choice and flexibility of deployment and updates.

**Pure open source innovation:**
The innovation in Kubernetes, serverless, service mesh, Kubernetes Operators, and more powered by the velocity of open source, with Red Hat in the lead.

== Next steps

If you would like to learn more about OpenShift Virtualization, please visit the https://www.redhat.com/en/technologies/cloud-computing/openshift/virtualization[landing page], review the https://docs.openshift.com/container-platform/latest/virt/about_virt/about-virt.html[documentation], or view some of our demo videos on https://www.youtube.com/playlist?list=PLaR6Rq6Z4IqeQeTosfoFzTyE_QmWZW6n_[YouTube].
