:scrollbar:
:toc2:
:numbered:

== オプションモジュール

以上で共通の 2 つのモジュールは終わりました。ここからはあなたの役割や興味に応じて、オプションのモジュールを行いましょう。

=== *仮想マシン管理者*

* 仮想マシンのカスタマイズ : +
仮想マシンを実行する際に最も重要なコンセプトの1つである、既存のディスクイメージから VM を実行し、VM をカスタマイズする機能について紹介します。
* Windows 仮想マシン : +
Microsoft Windows Server は一般的に使用されているオペレーティングシステムであり、これがサポートされていなければ仮想化ソリューションは完成しません！このラボでは、SysPrep によるカスタマイズを含む、Windows Server 仮想マシンのプロビジョニング方法の1つを紹介します。

=== *仮想インフラ管理者*

* ベアメタル OpenShift の概要 : +
OpenShift のノードとリソースの管理は、あなたが慣れ親しんでいる仮想インフラのものとは異なります。このモジュールでは、サーバハードウェアの責任者である場合に重要な OpenShift のいくつかの側面と概念について説明します。
* ネットワーク管理 : +
OpenShift Virtualization の仮想マシンは、デフォルトでは OpenShift 内部の SDN (Software-defined Network) に接続します。このセクションでは、VM を VLAN のような外部の物理ネットワークに接続する方法を説明します。
* ストレージ管理 : +
このモジュールでは、OpenShift 上のストレージの基礎と、OpenShift Virtualization がいくつかのマシンイメージのブートソースを自動的に提供する方法を紹介します。このモジュールでは、スナップショットを使った操作の実行方法と、VM のクローンを作成する方法も紹介します。
* バックアップとリストア : +
仮想マシンとそのデータを保護することは、パフォーマンスと可用性と同じくらい重要です。このラボでは、OpenShift API for Data Protection (OADP) がストレージに依存しない方法で VM を保護する方法を紹介します。

=== *仮想マシンユーザ*

* Route を使ったアプリケーションの公開 : +
このラボでは、Service と Route を使用してアプリケーション・コンポーネント間を内部で接続し、アプリケー ションのフロントエンドのみを外部に公開するプロセスについて説明します。
* MetalLB を使ったアプリケーションの公開 : +
VM を外部の L2 ネットワークに置くことなく、VM にホストされたアプリケーションに接続性を提供することは、アプリケーションへの接続性を管理する強力な方法です。このラボでは、VM を外部ネットワークに接続することなく、データベースだけを外部に公開するプロセスを説明します。

== Thank you for attending the OpenShift Virtualization workshop!

OepnShift Virtualization に慣れ親しんでいただくために、お時間と労力を割いていただきありがとうございます！ご不明な点がございましたら、ワークショップ中に会場にいるプロクターにご質問いただくか、いつでも Red Hat アカウントチームにお問い合わせください。

さらに OpenShift Virtualization について知りたい方は、次の情報ソースを訪問ご覧ください。

* https://www.redhat.com/ja/technologies/cloud-computing/openshift/virtualization[Red Hat OpenShift Virtualization Landing Page]
* https://docs.openshift.com/container-platform/latest/virt/about_virt/about-virt.html[OpenShift documentation], 
* https://www.youtube.com/playlist?list=PLaR6Rq6Z4IqeQeTosfoFzTyE_QmWZW6n_[YouTube Playlist].

